### PR TITLE
Added future dependency

### PR DESCRIPTION
**Pull request by martingoldammer**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=smoker-gate-PR79

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/smoker-merge-compliance-check/11/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/compliance/job/smoker-sonarqube-scan-zuul-el7/7/ : SUCCESS in 52s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/smoker-fossa-scanning-zuul-el7/7/ : SUCCESS in 1m 30s (non-voting)

**Pull request merged**
