### PR TITLE
PAAS-17589: Move dependencies to Requires clause in rpm spec file

### PR DESCRIPTION
**Pull request by Tjev**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=smoker-gate-PR81

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/smoker-merge-compliance-check/13/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/compliance/job/smoker-sonarqube-scan-zuul-el7/9/ : SUCCESS in 49s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/smoker-fossa-scanning-zuul-el7/9/ : SUCCESS in 1m 30s (non-voting)

**Pull request merged**
