### PR TITLE
PAAS-17323 Ensure setuptools version

### PR DESCRIPTION
**Pull request by martingoldammer**
Setuptools version should be at least 40.8.0 because solve PEP 517.

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=smoker-gate-PR76

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/smoker-merge-compliance-check/7/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/compliance/job/smoker-sonarqube-scan-zuul-el7/3/ : SUCCESS in 46s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/smoker-fossa-scanning-zuul-el7/3/ : SUCCESS in 1m 20s (non-voting)

**Pull request merged**
