### PR TITLE
TRIVIAL: Finish Python 3 support, fix/run tests and fix packaging

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Raits <igor.raits@gmail.com>

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by ignatenkobrain** [comment]
Replaced by https://github.com/gooddata/smoker/pull/83.

**Pull request closed without merging**
