### PR TITLE
WA-12252 - Truncate long component details

### PR DESCRIPTION
**Pull request by Slabimic**
Truncate component details currently longer than 256 chars.
Relates to #77

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=smoker-gate-PR78

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/smoker-merge-compliance-check/10/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/compliance/job/smoker-sonarqube-scan-zuul-el7/6/ : SUCCESS in 1m 02s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/smoker-fossa-scanning-zuul-el7/6/ : SUCCESS in 2m 26s (non-voting)

**Pull request merged**
