### PR TITLE
FEATURE: WA-12252 - Output contains component details of smoker output.

### PR DESCRIPTION
**Pull request by Slabimic**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=smoker-gate-PR77

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/smoker-merge-compliance-check/9/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/compliance/job/smoker-sonarqube-scan-zuul-el7/5/ : SUCCESS in 48s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/smoker-fossa-scanning-zuul-el7/5/ : SUCCESS in 1m 29s (non-voting)

**Pull request merged**
